import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const required = [
  "app/manifest.ts",
  "app/api/version/route.ts",
  "app/api/reports/export/route.ts",
  "app/pwa/route.ts",
  "app/pwa-error/page.tsx",
  "app/login/page.tsx",
  "app/register/page.tsx",
  "app/(dashboard)/overview/page.tsx",
  "app/(dashboard)/accounts/page.tsx",
  "app/(dashboard)/transactions/page.tsx",
  "app/(dashboard)/categories/page.tsx",
  "app/(dashboard)/settings/page.tsx",
  "app/(dashboard)/recurring/page.tsx",
  "app/(dashboard)/goals/page.tsx",
  "app/(dashboard)/deposits/page.tsx",
  "app/(dashboard)/loans/page.tsx",
  "app/(dashboard)/credit-cards/page.tsx",
  "features/credit-cards/actions.ts",
  "features/credit-cards/data.ts",
  "components/app-splash.tsx",
  "components/pending-submit-button.tsx",
  "components/navigation-progress.tsx",
  "components/instant-reveal.tsx",
  "components/instant-transaction-launcher.tsx",
  "components/recurring-rule-launcher.tsx",
  "features/recurring/actions.ts",
  "features/recurring/data.ts",
  "features/reports/data.ts",
  "features/goals/actions.ts",
  "features/goals/data.ts",
  "features/deposits/actions.ts",
  "features/deposits/data.ts",
  "features/loans/actions.ts",
  "features/loans/data.ts",
  "components/loan-simulator.tsx",
  "components/deposit-term-comparison.tsx",
  "app/(dashboard)/reports/page.tsx",
  "components/category-icon-picker.tsx",
  "components/transaction-category-select.tsx",
  "components/pwa-register.tsx",
  "features/accounts/actions.ts",
  "features/transactions/actions.ts",
  "features/transactions/data.ts",
  "features/categories/actions.ts",
  "features/categories/constants.ts",
  "features/categories/data.ts",
  "features/categories/icons.tsx",
  "features/budgets/actions.ts",
  "features/budgets/data.ts",
  "lib/app-version.ts",
  "lib/auth.ts",
  "lib/supabase/client.ts",
  "lib/supabase/server.ts",
  "lib/supabase/proxy.ts",
  "proxy.ts",
  "supabase/migrations/20261005110000_foundation_environment.sql",
  "supabase/migrations/20261006134500_account_core.sql",
  "supabase/migrations/20261006150000_transaction_core.sql",
  "supabase/migrations/20261006160000_category_engine.sql",
  "supabase/migrations/20261006170000_budget_engine.sql",
  "supabase/migrations/20261006180000_recurring_calendar.sql",
  "supabase/migrations/20261007110000_savings_goals.sql",
  "supabase/migrations/20261007123000_interest_deposit_manager.sql",
  "supabase/migrations/20261007143000_loan_debt_manager.sql",
  "supabase/migrations/20261007160000_credit_card_manager.sql",
  "supabase/sql-editor/V0.0.5_category_engine.sql",
  "supabase/sql-editor/V0.0.5_category_engine_verify.sql",
  "supabase/sql-editor/V0.0.6_budget_engine.sql",
  "supabase/sql-editor/V0.0.6_budget_engine_verify.sql",
  "supabase/sql-editor/V0.0.7_recurring_calendar.sql",
  "supabase/sql-editor/V0.0.7_recurring_calendar_verify.sql",
  "supabase/sql-editor/V0.0.8_reports_insights_verify.sql",
  "supabase/sql-editor/V0.0.9_savings_goals.sql",
  "supabase/sql-editor/V0.0.9_savings_goals_verify.sql",
  "supabase/sql-editor/V0.0.10_interest_deposit_manager.sql",
  "supabase/sql-editor/V0.0.10_interest_deposit_manager_verify.sql",
  "supabase/sql-editor/V0.0.11_loan_debt_manager.sql",
  "supabase/sql-editor/V0.0.11_loan_debt_manager_verify.sql",
  "supabase/sql-editor/V0.0.12_credit_card_manager.sql",
  "supabase/sql-editor/V0.0.12_credit_card_manager_verify.sql",
  "supabase/tests/category-engine.test.sql",
  "supabase/tests/budget-engine.test.sql",
  "supabase/tests/recurring-calendar.test.sql",
  "supabase/tests/savings-goals.test.sql",
  "supabase/tests/interest-deposit-manager.test.sql",
  "supabase/tests/loan-debt-manager.test.sql",
  "supabase/tests/credit-card-manager.test.sql",
  "docs/V0.0.5_CATEGORY_ENGINE_SETUP.md",
  "docs/V0.0.6_BUDGET_ENGINE_SETUP.md",
  "docs/V0.0.7_RECURRING_CALENDAR_SETUP.md",
  "docs/V0.0.8_REPORTS_PWA_AUTH_SETUP.md",
  "docs/V0.0.9_SAVINGS_GOALS_SETUP.md",
  "docs/V0.0.10_INTEREST_DEPOSIT_MANAGER_SETUP.md",
  "docs/V0.0.11_LOAN_DEBT_MANAGER_SETUP.md",
  "docs/V0.0.12_CREDIT_CARD_MANAGER_SETUP.md",
  "public/sw.js",
  ".env.example",
  "vercel.json"
];

test("V0.0.12 required files exist", () => {
  for (const file of required) assert.equal(existsSync(file), true, `${file} is missing`);
});

test("package version is 0.0.12", () => {
  const pkg = JSON.parse(readFileSync("package.json", "utf8"));
  assert.equal(pkg.version, "0.0.12");
  assert.match(pkg.dependencies.next, /16/);
  assert.ok(pkg.dependencies["@supabase/ssr"]);
});
